module.exports = [
  { name: 'Rice', description: 'Everyday and premium rice varieties' },
  { name: 'Flour & Atta', description: 'Wheat flour, atta, maida and suji' },
  { name: 'Lentils', description: 'Dal and pulses for daily cooking' },
  { name: 'Cooking Oil', description: 'Soybean, mustard and sunflower oils' },
  { name: 'Ghee', description: 'Pure and blended ghee' },
  { name: 'Salt', description: 'Iodized and rock salt' },
  { name: 'Sugar', description: 'White, brown and icing sugar' },
  { name: 'Spices', description: 'Whole and ground spices' },
  { name: 'Tea', description: 'Black, green and specialty tea' },
  { name: 'Coffee', description: 'Instant and ground coffee' },
  { name: 'Milk Powder', description: 'Full cream and skimmed milk powder' },
  { name: 'Beverages', description: 'Juices and flavoured drinks' },
  { name: 'Soft Drinks', description: 'Carbonated soft drinks' },
  { name: 'Mineral Water', description: 'Bottled drinking water' },
  { name: 'Biscuits', description: 'Cream, glucose and digestive biscuits' },
  { name: 'Snacks', description: 'Chips, chanachur and savoury snacks' },
  { name: 'Noodles', description: 'Instant and dry noodles' },
  { name: 'Breakfast Items', description: 'Cereals and breakfast essentials' },
  { name: 'Honey', description: 'Pure and flavoured honey' },
  { name: 'Dates', description: 'Premium and everyday dates' },
  { name: 'Dry Fruits', description: 'Nuts and dried fruits' },
  { name: 'Seeds', description: 'Chia and other superseeds' },
  { name: 'Oats', description: 'Rolled and instant oats' },
  { name: 'Peanut Butter', description: 'Smooth and crunchy peanut butter' },
  { name: 'Jam', description: 'Fruit jams and spreads' },
  { name: 'Jelly', description: 'Fruit jelly and preserves' },
  { name: 'Pickles', description: 'Traditional mixed pickles' },
  { name: 'Sauces', description: 'Cooking and table sauces' },
  { name: 'Tomato Ketchup', description: 'Tomato ketchup and chili sauce' },
  { name: 'Mayonnaise', description: 'Mayonnaise and dressings' },
  { name: 'Frozen Food', description: 'Ready-to-cook frozen items' },
  { name: 'Eggs', description: 'Farm fresh eggs' },
  { name: 'Baby Food', description: 'Infant formula and baby cereal' },
  { name: 'Instant Food', description: 'Ready-to-eat and instant meals' },
  { name: 'Tissue', description: 'Facial and toilet tissue' },
  { name: 'Soap', description: 'Bathing and hand soap' },
  { name: 'Shampoo', description: 'Hair care shampoo' },
  { name: 'Toothpaste', description: 'Oral care essentials' },
  { name: 'Dish Wash', description: 'Dish washing liquid and bars' },
  { name: 'Detergent', description: 'Laundry detergent powder and liquid' },
  { name: 'Cleaning Supplies', description: 'Home cleaning essentials' },
];
